In [22]:
import numpy as np
import pandas as pd

### load file using numpy


In [23]:
data = np.genfromtxt('data.txt', delimiter=',', filling_values=0)
data = data.astype('int32')
data

array([[ 1,  3,  5,  7,  9, 11,  0],
       [13, 15, 17, 19, 21, 23, 25],
       [27, 29,  1,  4,  7, 10,  0],
       [13, 16, 19, 22, 25, 28, 28]], dtype=int32)

In [24]:
data[data>10]
# data>15   

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 13, 16, 19, 22, 25, 28, 28],
      dtype=int32)

In [25]:
data[1:4, 0:2]
# data
data[[0, 2]]

array([[ 1,  3,  5,  7,  9, 11,  0],
       [27, 29,  1,  4,  7, 10,  0]], dtype=int32)

In [26]:
# if column(axis = 0) contain value greater than 20
# tilde sign for element wise negation
np.all(~(data>20), axis=0) 


array([False, False,  True, False, False, False, False])

In [27]:
output = data[(data>20)]
output

array([21, 23, 25, 27, 29, 22, 25, 28, 28], dtype=int32)

In [28]:
pop = pd.Series([35.2, 48.2, 45.8, 34.7, 72.1])
pop

0    35.2
1    48.2
2    45.8
3    34.7
4    72.1
dtype: float64

In [36]:
pop.index
pop.name = "Population of cities"
pop

Quetta       34.7
Islamabad    35.2
Peshawer     45.8
Lahore       48.2
Karachi      72.1
Name: Population of cities, dtype: float64

In [30]:
cities = ['Islamabad', 'Lahore', 'Peshawer', 'Quetta', 'Karachi']
pop.index = cities
pop

Islamabad    35.2
Lahore       48.2
Peshawer     45.8
Quetta       34.7
Karachi      72.1
dtype: float64

In [32]:
pop['Islamabad']
pop[0] #deprecated

C:\Users\abbas\AppData\Local\Temp\ipykernel_2480\1694679690.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  pop[0]


np.float64(35.2)

In [33]:
pop = pop.sort_values()
pop

Quetta       34.7
Islamabad    35.2
Peshawer     45.8
Lahore       48.2
Karachi      72.1
dtype: float64

In [ ]:
pop.iloc[0]
# pop.iloc[1:3]
# pop.Islamabad
pop[0:4] #4th element not included
pop['Quetta':'Karachi'] #all elements are inclusive

Quetta       34.7
Islamabad    35.2
Peshawer     45.8
Lahore       48.2
Karachi      72.1
Name: Population of cities, dtype: float64

In [56]:
pop*10_000
pop.std()
pop.median()
pop.mean()
np.log(pop)

Quetta       3.546740
Islamabad    3.561046
Peshawer     3.824284
Lahore       3.875359
Karachi      4.278054
Name: Population of cities, dtype: float64